apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: busybox-go-operator-dc
spec:
  replicas: 1
  selector:
      name: busybox-go-operator-dc
  template:
    metadata:
      labels:
        name: busybox-go-operator-dc
    spec:
      serviceAccountName: busybox-go-operator-dc
      containers:
        - name: busybox-go-operator-dc
          # Replace this with the built image name
          image: quay.io/eacmesquita96/busybox-go-operator:v0.1
          command:
          - busybox-go-operator-dc
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "busybox-go-operator-dc"
