kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: busybox-go-operator-dc
subjects:
- kind: ServiceAccount
  name: busybox-go-operator-dc
roleRef:
  kind: Role
  name: busybox-go-operator-dc
  apiGroup: rbac.authorization.k8s.io
